# Generated by Django 2.0.5 on 2018-05-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='City', max_length=64)),
                ('image', models.URLField(default='https://images.pexels.com/photos/139229/pexels-photo-139229.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260')),
                ('price', models.FloatField(default=0.0)),
                ('dpt', models.TextField(default='Colombia')),
                ('iata', models.CharField(default='COL', max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
